config/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from config import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('contact.urls')),

    path('', include('edu.urls')),

    path('products/', include('product.urls')),

] +  debug_toolbar_urls()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
    
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),

]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.product_list, name='product_list'),

]

contact/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=25)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    message = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message[:10] + ('...' if len(self.message) > 10 else '')

product/models.py
from django.db import models
from django.utils.text import slugify


class Modified(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Product(Modified):
    name = models.CharField(max_length=100)                           # <input type='text'>
    description = models.TextField(default='', blank=True)            # <textarea></textarea>
    price = models.DecimalField(max_digits=6, decimal_places=2)       # <input type='number'>
    stock_count = models.IntegerField(help_text='How many items are currently in stock')
    sku = models.CharField(max_length=20, verbose_name='Stock Keeping Unit')
    slug = models.SlugField(unique=True, blank=True)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    image = models.ImageField(upload_to='products_images')      # PiL (Pillow)
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='images')

    def __str__(self):
        return str(self.image)

class Category(models.Model):
    name = models.CharField(max_length=20)
    products = models.ManyToManyField('Product', related_name='categories')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'
        verbose_name = 'Product Category'
        ordering = ('name',)

contact/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def contact(request):
    return render(request, 'contact/contact.html')

home/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    return render(request, 'home/home.html')

# Create your views here.

product/views.py
from django.shortcuts import render

from . import models
# Create your views here.
def product_list(request):
    products = models.Product.objects.all()
    return render(request, 'product/products.html', {'products': products})

contact/templates/contact/contact.html
{% extends 'base.html' %}
{% block title %}contact{% endblock %}
{% block container %}

    <h1>Contact</h1>

{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}

{% block title %}home{% endblock %}

{% block container %}

    <h1> ALEgrosz</h1>

{% endblock %}

product/templates/product/products.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Product list{% endblock %}


{% block header %}
{% endblock %}

{% block container %}
    <h1>Product list</h1>

    <div>
        {% for product in products %}
            <h2>{{ product.name }}</h2>
            <img src="/media/{{ product.images.all.0 }}" alt="{{ product.name }}">
{#            <p>{{  product.images.all.0}}</p>#}
            <p>{{ product.description }}</p>
            <p>Cena: <b>{{ product.price }}</b></p>

        {% endfor %}
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Alegrosz - {% block title %}{% endblock %}</title>

    {% block styles %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock %}

    {% block scripts %}
        <script src="{% static 'scripts/bootstrap.bundle.min.js' %}" async defer></script>
    {% endblock %}

</head>
<body>

{% block header %}
{% endblock %}




{% include 'partials/nav.html' %}

<div class="container">
    <div class="row">
        <div class="col-12 col-md-8">
            {% block container %}{% endblock %}
        </div>
        <div class="col-12 col-md-4">
            {% block aside %}Aside{% endblock %}
        </div>
    </div>

</div>
</body>
</html>

templates/partials/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:home' %}">
        <img class="logo" src="{% static 'images/logo.svg' %}" alt="Logo Alegrosz">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'product:product_list' %}">Product</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>



<nav>
    <a href="{% url 'home:home' %}">Home</a> <br>
    <a href="{% url 'contact:contact' %}">Contact</a> <br>
    <a href="{% url 'edu:lotto_view' %}">lotto</a> <br>
    <a href="{% url 'edu:eurojackpot_view' %}">euro_jackpot</a> <br>
    <a href="{% url 'product:product_list' %}">Product</a> <br>
</nav>